
REFERENCE = ['keine Eingabe', 'keine Eingabe', 'keine Eingabe']
# WIND-DATEN
LIST_WIND = []
HERSTELLER_WIND = []
MODELL_WIND = []
STANDORT_WIND = []
ANZAHL_WIND = []

#SOLAR-DATEN
LIST_SOLAR = []
HERSTELLER_SOLAR = []
MODELL_SOLAR = []
STANDORT_SOLAR = []
FLAECHE_SOLAR = []

#SPEICHER-DATEN
LIST_SPEICHER = []
ANLAGE_SPEICHER = []
ANZAHL_SPEICHER = []

#FAKTOREN
FAKTOREN_LIST = []

